// Generated by Classiq.
// Classiq version: 0.29.1
// Creation timestamp: 2023-10-01T02:33:03.670089+00:00
// Random seed: 1693797141

OPENQASM 2.0;
include "qelib1.inc";
gate mcx_140100926154832 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140100926158160 q0,q1,q2,q3 {
  mcx_140100926154832 q0,q1,q2,q3;
}

gate statepreparation_rygate_10_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140100926158160 q0,q1,q2,q3;
}

gate statepreparation_rygate_10 q0,q1,q2,q3 {
  statepreparation_rygate_10_mcx_0 q1,q2,q3,q0;
  ry(-pi/4) q0;
  statepreparation_rygate_10_mcx_0 q1,q2,q3,q0;
  ry(pi/4) q0;
}

gate mcx_140100782951056 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140101386016848 q0,q1,q2,q3 {
  mcx_140100782951056 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140101386016848_o5 q0,q1,q2,q3 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140101386016848 q0,q1,q2,q3;
  x q1;
}

gate statepreparation_rygate_9_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140101386016848_o5 q0,q1,q2,q3;
}

gate statepreparation_rygate_9 q0,q1,q2,q3 {
  statepreparation_rygate_9_mcx_0 q1,q2,q3,q0;
  ry(pi/4) q0;
  statepreparation_rygate_9_mcx_0 q1,q2,q3,q0;
  ry(-pi/4) q0;
}

gate mcx_140100794146896 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140100794168144 q0,q1,q2,q3 {
  mcx_140100794146896 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140100794168144_o3 q0,q1,q2,q3 {
  x q2;
  mcx_hybrid_gray_code_maslov15_140100794168144 q0,q1,q2,q3;
  x q2;
}

gate statepreparation_rygate_8_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140100794168144_o3 q0,q1,q2,q3;
}

gate statepreparation_rygate_8 q0,q1,q2,q3 {
  statepreparation_rygate_8_mcx_0 q1,q2,q3,q0;
  ry(pi/4) q0;
  statepreparation_rygate_8_mcx_0 q1,q2,q3,q0;
  ry(-pi/4) q0;
}

gate mcx q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140100942497936 q0,q1,q2,q3 {
  mcx q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140100942497936_o0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15_140100942497936 q0,q1,q2,q3;
  x q0;
  x q1;
  x q2;
}

gate statepreparation_rygate_7_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140100942497936_o0 q0,q1,q2,q3;
}

gate statepreparation_rygate_7 q0,q1,q2,q3 {
  statepreparation_rygate_7_mcx_0 q1,q2,q3,q0;
  ry(pi/4) q0;
  statepreparation_rygate_7_mcx_0 q1,q2,q3,q0;
  ry(-pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140101368335824 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate statepreparation_rygate_6_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140101368335824 q0,q1,q2;
}

gate statepreparation_rygate_6 q0,q1,q2 {
  statepreparation_rygate_6_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
  statepreparation_rygate_6_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140100792972112 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140100792972112_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140100792972112 q0,q1,q2;
  x q0;
}

gate statepreparation_rygate_5_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140100792972112_o2 q0,q1,q2;
}

gate statepreparation_rygate_5 q0,q1,q2 {
  statepreparation_rygate_5_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
  statepreparation_rygate_5_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140100926102800 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140100926102800_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140100926102800 q0,q1,q2;
  x q1;
}

gate statepreparation_rygate_4_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140100926102800_o1 q0,q1,q2;
}

gate statepreparation_rygate_4 q0,q1,q2 {
  statepreparation_rygate_4_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
  statepreparation_rygate_4_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140100942509712 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140100942509712_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140100942509712 q0,q1,q2;
  x q0;
  x q1;
}

gate statepreparation_rygate_3_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140100942509712_o0 q0,q1,q2;
}

gate statepreparation_rygate_3 q0,q1,q2 {
  statepreparation_rygate_3_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
  statepreparation_rygate_3_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140100942496720 q0,q1 {
  cx q0,q1;
}

gate statepreparation_rygate_2_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140100942496720 q0,q1;
}

gate statepreparation_rygate_2 q0,q1 {
  statepreparation_rygate_2_mcx_0 q1,q0;
  statepreparation_rygate_2_mcx_0 q1,q0;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate statepreparation_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_rygate_1 q0,q1 {
  statepreparation_rygate_1_mcx_0 q1,q0;
  statepreparation_rygate_1_mcx_0 q1,q0;
}

gate statepreparation q0,q1,q2,q3 {
  h q0;
  h q1;
  h q2;
  h q3;
  ry(0) q3;
  statepreparation_rygate_1 q2,q3;
  statepreparation_rygate_2 q2,q3;
  statepreparation_rygate_3 q1,q2,q3;
  statepreparation_rygate_4 q1,q2,q3;
  statepreparation_rygate_5 q1,q2,q3;
  statepreparation_rygate_6 q1,q2,q3;
  statepreparation_rygate_7 q0,q1,q2,q3;
  statepreparation_rygate_8 q0,q1,q2,q3;
  statepreparation_rygate_9 q0,q1,q2,q3;
  statepreparation_rygate_10 q0,q1,q2,q3;
}

qreg q[4];
statepreparation q[0],q[1],q[2],q[3];
